# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fl_starter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66l_starter.proto\x12\x11\x46\x65\x64\x65ratedLearning\"J\n\x07Request\x12\x11\n\tclient_id\x18\x01 \x01(\x03\x12\x14\n\x0crequest_data\x18\x02 \x01(\t\x12\x16\n\x0erequest_status\x18\x03 \x01(\x05\"M\n\x08Response\x12\x11\n\tserver_id\x18\x01 \x01(\x03\x12\x15\n\rresponse_data\x18\x02 \x01(\t\x12\x17\n\x0fresponse_status\x18\x03 \x01(\x05\x32\xc5\x02\n\x07Trainer\x12N\n\x11InitialiseWeights\x12\x1a.FederatedLearning.Request\x1a\x1b.FederatedLearning.Response\"\x00\x12O\n\x0eTrainedWeights\x12\x1a.FederatedLearning.Request\x1a\x1b.FederatedLearning.Response\"\x00(\x01\x30\x01\x12K\n\x0cMultiRequest\x12\x1a.FederatedLearning.Request\x1a\x1b.FederatedLearning.Response\"\x00(\x01\x12L\n\rMultiResponse\x12\x1a.FederatedLearning.Request\x1a\x1b.FederatedLearning.Response\"\x00\x30\x01\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'fl_starter_pb2'
  # @@protoc_insertion_point(class_scope:FederatedLearning.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'fl_starter_pb2'
  # @@protoc_insertion_point(class_scope:FederatedLearning.Response)
  })
_sym_db.RegisterMessage(Response)

_TRAINER = DESCRIPTOR.services_by_name['Trainer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=39
  _REQUEST._serialized_end=113
  _RESPONSE._serialized_start=115
  _RESPONSE._serialized_end=192
  _TRAINER._serialized_start=195
  _TRAINER._serialized_end=520
# @@protoc_insertion_point(module_scope)
